# Generated by Django 4.1.5 on 2023-01-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0002_project_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_foreign', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='???')),
                ('logo', models.TextField(verbose_name='???')),
                ('status', models.CharField(choices=[(1, 'bachelor'), (2, 'master')], default='bachelor', max_length=15, verbose_name='Статус')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.region', verbose_name='???')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='???')),
                ('name', models.CharField(max_length=255, verbose_name='???')),
                ('midname', models.CharField(max_length=255, verbose_name='???')),
                ('bachelors_start_year', models.TextField(blank=True, null=True, verbose_name='???')),
                ('masters_start_year', models.TextField(blank=True, null=True, verbose_name='???')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Забанен ли игрок')),
                ('groups', models.ManyToManyField(to='events.event', verbose_name='События')),
                ('projects', models.ManyToManyField(to='projects.project', verbose_name='Проекты')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.university', verbose_name='???')),
                ('user', models.OneToOneField(blank=True, help_text='Каждый пользователь имеет свой profile', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
