# Generated by Django 4.1.5 on 2023-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('start', models.DateField(verbose_name='Дата началы мероприятия')),
                ('end', models.DateField(verbose_name='Дата конца мероприятия')),
                ('desc', models.TextField(verbose_name='Описание мероприятия')),
                ('is_frozen', models.IntegerField(verbose_name='Заморожено ли мероприятие (для тех, которые в процессе планирования\\реализации пришлось отложить)')),
            ],
        ),
    ]
