# Generated by Django 4.1.5 on 2023-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_company'),
        ('students', '0002_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(to='projects.project', verbose_name='Проекты'),
        ),
    ]
